---
title: Panel Data and Current Methods
jupyter: python3
---

This section will provide an introduction to panel data and a brief overview of the classic econometric methods for model data with this structure, highligting it's beneficts and shortcommings.


lets assume we have 
$$
y_{it}=\alpha + x'_{it}\beta +e_{it}
$$

then we have two main ways for estimating it:

# Models

## Fixed Effects (FE)

- treats $\alpha_i$ as an unobserved random variable that can be correlated with the errors.
- So $\alpha_1,...,\alpha_N$ are parameters to be estimated.
- The modern econometrics literature preffer this ones.
- in short panels: permits only identification of the marginal effects only for time-varying regressors. Because all the rest is caputured by the fixed effect (dummy)
- $\alpha_i$ estimation is not consistent and shouldn't be estimated
- provide conditional predictors

# two wat fixed effecs
- Combines both effects for $i$ and $t$
$$
y_{it}=\alpha_i+\gamma_t+x_{it}\beta\epsilon_{it}
$$


## Random Effects (RE)
- assumes that the unobserbable individual effects of $\alpha_i$ are distributed independently of the regressors.
- So the random effects are assumed to be i.i.d
- permits identification of everything
- provide population level preds

# Estimators
## OLS

$$
y_it=\alpha+x_{it}\beta+(\alpha_i-\alpha+\epsilon_{it})
$$

- fails because errors are of individuals $i$ are usually correlated over $t$
- only appropiatte if the constant coefficients or random effects models are appropiatted
- inconsistent if FE is appropiatte.

## Between estimator
$$
\bar{y}_it=\alpha+\bar{x}_{it}\beta+(\alpha_i-\alpha+\\bar{epsilon}_{it})
$$

- uses just cross-sectional variation, so it averages over all years $\bar{y}_i=\alpha_i+\bar{x}_i\beta+\bar{\epsilon}_i$
- it's like cross section with $T=1$
- is consistent with RE, not with FE

## Within Estimator (or FE)
$$
y_{it}-\bar{t} = (x_{it}-\bar{x}_i)'\beta+(\epsilon_{it}-\bar{\epsilon}_i)
$$

- the $\alpha_i$ terms cancel
- an alternative would be to use least-squares dummy variable estimation
- coefficients of time-invariant regressors are not identified in the within model

# Errors
- check what needs to be done for controlling for errors, given that there might be serial correlation on i.
- cluster-standard errors
- the standard robust standard error option only adjuststs for heteroskedasticity. Corrects error serial correlation and autocorrelation.